-- Seed subkegiatan from provided list
-- Clears existing data then inserts new rows

DELETE FROM subkegiatan;

INSERT INTO subkegiatan (subkegiatan, ppk, status, created_at, updated_at) VALUES
('Penyusunan Dokumen Perencanaan Perangkat Daerah', 'PERENCANAAN', 'active', datetime('now'), datetime('now')),
('Koordinasi dan Penyusunan Dokumen RKA-SKPD', 'PERENCANAAN', 'active', datetime('now'), datetime('now')),
('Koordinasi dan Penyusunan Dokumen Perubahan RKA-SKPD', 'PERENCANAAN', 'active', datetime('now'), datetime('now')),
('Koordinasi dan Penyusunan Laporan Capaian Kinerja dan Ikhtisar Realisasi Kinerja SKPD', 'PERENCANAAN', 'active', datetime('now'), datetime('now')),
('Dukungan Pelaksanaan Sistem Pemerintahan Berbasis Elektronik pada SKPD', 'PERENCANAAN', 'active', datetime('now'), datetime('now')),
('Penyediaan Gaji dan Tunjangan ASN', 'KEUANGAN', 'active', datetime('now'), datetime('now')),
('Koordinasi dan Penyusunan Laporan Keuangan Bulanan/Triwulanan/ Semesteran SKPD', 'KEUANGAN', 'active', datetime('now'), datetime('now')),
('Penyuluhan dan Penyebarluasan Kebijakan Retribusi Daerah', 'KEUANGAN', 'active', datetime('now'), datetime('now')),
('Pendataan dan Pendaftaran Objek Retribusi Daerah', 'KEUANGAN', 'active', datetime('now'), datetime('now')),
('Pelaporan Pengelolaan Retribusi Daerah', 'KEUANGAN', 'active', datetime('now'), datetime('now')),
('Pelaksanaan Penatausahaan dan Pengujian/Verifikasi Keuangan SKPD', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Pengadaan Pakaian Dinas beserta Atribut Kelengkapannya', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Bimbingan Teknis Implementasi Peraturan Perundang-Undangan', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Penyediaan Komponen Instalasi Listrik/Penerangan Bangunan Kantor', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Penyediaan Peralatan dan Perlengkapan Kantor', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Penyediaan Peralatan Rumah Tangga', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Penyediaan Bahan Logistik Kantor', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Penyediaan Barang Cetakan dan Penggandaan', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Penyediaan Bahan Bacaan dan Peraturan Perundang-undangan', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Penyelenggaraan Rapat Koordinasi dan Konsultasi SKPD', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Pengadaan Kendaraan Perorangan Dinas atau Kendaraan Dinas Jabatan', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Pengadaan Kendaraan Dinas Operasional atau Lapangan', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Pengadaan Sarana dan Prasarana Gedung Kantor atau Bangunan Lainnya', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Penyediaan Jasa Surat Menyurat', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Penyediaan Jasa Komunikasi, Sumber Daya Air dan Listrik', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Penyediaan Jasa Peralatan dan Perlengkapan Kantor', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Penyediaan Jasa Pelayanan Umum Kantor', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Penyediaan Jasa Pemeliharaan, Biaya Pemeliharaan, dan Pajak Kendaraan Perorangan Dinas atau Kendaraan Dinas Jabatan', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Penyediaan Jasa Pemeliharaan, Biaya Pemeliharaan, Pajak dan Perizinan Kendaraan Dinas Operasional atau Lapanga', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Pemeliharaan/Rehabilitasi Gedung Kantor dan Bangunan Lainnya', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Pemeliharaan/Rehabilitasi Sarana dan Prasarana Gedung Kantor atau Bangunan Lainnya', 'UMPAR', 'active', datetime('now'), datetime('now')),
('Pengelolaan Laboratorium Lingkungan Hidup Kabupaten/kota', 'UPT LAB', 'active', datetime('now'), datetime('now')),
('Penanganan sampah melalui pemrosesan akhir sampah di TPA/TPST kabupaten/kota atau TPA/TPST Regional', 'UPTD TPA', 'active', datetime('now'), datetime('now')),
('Pengendalian Pelaksanaan RPPLH Kabupaten/Kota', 'TALING', 'active', datetime('now'), datetime('now')),
('Penyelenggaraan KLHS untuk KRP yang Berpotensi Menimbulkan Dampak/Resiko Lingkungan Hidup', 'TALING', 'active', datetime('now'), datetime('now')),
('Pengelolaan Taman Keanekaragaman Hayati Lainnya', 'TALING', 'active', datetime('now'), datetime('now')),
('Pengelolaan Ruang Terbuka Hijau', 'TALING', 'active', datetime('now'), datetime('now')),
('Pendampingan Gerakan Peduli Lingkungan Hidup', 'P2KLH', 'active', datetime('now'), datetime('now')),
('Penyelenggaraan Penyuluhan dan Kampanye Lingkungan Hidup', 'P2KLH', 'active', datetime('now'), datetime('now')),
('Penilaian Kinerja Masyarakat/Lembaga Masyarakat/Dunia Usaha/Dunia Pendidikan/Filantropi dalam Perlindungan dan Pengelolaan Lingkungan Hidup', 'P2KLH', 'active', datetime('now'), datetime('now')),
('Peningkatan Kapasitas dan Kompetensi Sumber Daya Manusia Bidang lingkungan hidup untuk Lembaga pendidikan formal/lembaga masyarakat/komunitas/kelompok masyarakat', 'P2KLH', 'active', datetime('now'), datetime('now')),
('Penerapan Sanksi Administrasi yang Menjadi Kewenangan Kabupaten/Kota', 'P2KLH', 'active', datetime('now'), datetime('now')),
('Pengawasan Perizinan Berusaha atau Persetujuan Pemerintah Terkait Persetujuan Lingkungan yang diterbitkan oleh Pemerintah Daerah Kabupaten/Kota dan Peraturan Perundang-undangan di bidang Perlindungan dan Pengelolaan Lingkungan Hidup', 'P2KLH', 'active', datetime('now'), datetime('now')),
('Penyelesaian sengketa lingkungan hidup yang ditangani yang menjadi kewenangan kabupaten/kota', 'P2KLH', 'active', datetime('now'), datetime('now')),
('Pengembangan Kapasitas Pejabat Pengawas Lingkungan Hidup', 'P2KLH', 'active', datetime('now'), datetime('now')),
('Fasilitasi Pemenuhan Ketentuan dan Kewajiban Izin Lingkungan dan/atau Izin PPLH', 'P2KLH', 'active', datetime('now'), datetime('now')),
('Pengelolaan Pengaduan permasalahan Pencemaran dan Perusakan Lingkungan Hidup tingkat Kabupaten/Kota', 'P2KLH', 'active', datetime('now'), datetime('now')),
('Pelaksanaan pemantauan kualitas Lingkungan Hidup terhadap Media Tanah, Air, Udara, dan Laut', 'P2KL', 'active', datetime('now'), datetime('now')),
('Pengoperasian dan pemeliharaan alat pemantau kualitas lingkungan di kabupaten/kota', 'P2KL', 'active', datetime('now'), datetime('now')),
('Pelaksanaan upaya mitigasi perubahan iklim tingkat kabupaten/kota', 'P2KL', 'active', datetime('now'), datetime('now')),
('Penyusunan dokumen status lingkungan hidup daerah', 'P2KL', 'active', datetime('now'), datetime('now')),
('Pengisolasian Pencemaran dan/atau Kerusakan Lingkungan Hidup', 'P2KL', 'active', datetime('now'), datetime('now')),
('Koordinasi dan Sinkronisasi Penghentian Sumber Pencemaran', 'P2KL', 'active', datetime('now'), datetime('now')),
('Koordinasi dan Sinkronisasi Pembersihan Unsur Pencemar di kabupaten/kota', 'P2KL', 'active', datetime('now'), datetime('now')),
('Pengoperasian dan pemeliharaan sarana penanganan sampah', 'PSLB3', 'active', datetime('now'), datetime('now')),
('Koordinasi, Sinkronisasi dan Pelaksanaan Penanganan Sampah pada Kondisi Khusus', 'PSLB3', 'active', datetime('now'), datetime('now')),
('penanganan sampah melalui pengangkutan', 'PSLB3', 'active', datetime('now'), datetime('now')),
('penanganan sampah melalui pengoperasian dan pemeliharaan sarana dan prasarana penanganan sampah', 'PSLB3', 'active', datetime('now'), datetime('now')),
('Penanganan sampah melalui pengumpulan sampah', 'PSLB3', 'active', datetime('now'), datetime('now')),
('Fasilitasi Pemenuhan Komitmen Izin Penyimpanan sementara Limbah B3 Dilaksanakan Melalui Sistem Pelayanan Perizinan', 'PSLB3', 'active', datetime('now'), datetime('now')),
('Verifikasi Lapangan untuk Memastikan Pemenuhan Persyaratan Administrasi dan Teknis Penyimpanan sementara Limbah B3', 'PSLB3', 'active', datetime('now'), datetime('now')),
('Fasilitasi Pemenuhan Komitmen Izin Pengumpulan Limbah B3 Dilaksanakan Melalui Sistem Pelayanan Perizinan Berusaha Terintegrasi Secara Elektronik', 'PSLB3', 'active', datetime('now'), datetime('now')),
('Peningkatan Peran Serta Masyarakat dalam Pengelolaan Persampahan', 'PSLB3', 'active', datetime('now'), datetime('now')),
('Penyusunan Rencana, Kebijakan dan Strategi Daerah Pengelolaan Sampah kabupaten/kota', 'PSLB3', 'active', datetime('now'), datetime('now')),
('Pengurangan sampah melalui pemanfaatan kembali sampah', 'PSLB3', 'active', datetime('now'), datetime('now')),
('Penanganan sampah melalui pemilahan dan pengolahan sampah di instalasi pengolahan sampah TPS3R, PDU, TPST, TPS, SPA, PSEL/PLTSa, RDF, pusat pengomposan, biodigester, Bank Sampah dan fasilitas lainnya sesuai dengan peraturan perundangan', 'PSLB3', 'active', datetime('now'), datetime('now')),
('Pengurangan sampah melalui pembatasan timbulan sampah', 'PSLB3', 'active', datetime('now'), datetime('now')),
('Pengurangan sampah melalui pendauran ulang sampah', 'PSLB3', 'active', datetime('now'), datetime('now'));
